
JACK_REPR = "J"
QUEEN_REPR = "Q"
KING_REPR = "K"
ACE_REPR = "A"
RED_JOKER_REPR = "RJ"
BLACK_JOKER_REPR = "BJ"

SPECIAL_CARDS_MAP = {1:ACE_REPR, 11:JACK_REPR, 12:QUEEN_REPR, 
    13:KING_REPR, 14:BLACK_JOKER_REPR, 15:RED_JOKER_REPR}